import { Session } from "../models/session.model"
import { Snippet } from "../models/snippet.model"

// const defaultKit: Snippet[] = [{
//     name: 'kick',
//     fileName: '',
//     volume: 1,
//     pan: 0,
//     highPassFrequency: 0,
//     lowPassFrequency: 22050,
//     pitch: 1,
//     isMuted: false,
//     src: '../../../assets/samples/KAVARI - Texture Vice -Sample Pack- - 129 KAVARI Kick 5.wav',
//     playable: new Array<boolean>(32).fill(false),
//     buffer: '',
//     key: 'q'
// }, {
//     name: 'snare',
//     fileName: '',
//     volume: 1,
//     pan: 0,
//     highPassFrequency: 0,
//     lowPassFrequency: 22050,
//     pitch: 1,
//     isMuted: false,
//     src: '../../../assets/samples/Snare 14 DSP 808.wav',
//     playable: new Array<boolean>(32).fill(false),
//     buffer: '',
//     key: 'p'
// }, {
//     name: 'hihat',
//     fileName: '',
//     volume: 1,
//     pan: 0,
//     highPassFrequency: 0,
//     lowPassFrequency: 22050,
//     pitch: 1,
//     isMuted: false,
//     src: '../../../assets/samples/CLASSIC HH.wav',
//     playable: new Array<boolean>(32).fill(false),
//     buffer: '',
//     key: 'w'
// }, {
//     name: 'perc',
//     fileName: '',
//     volume: 0.5,
//     pan: 0,
//     highPassFrequency: 0,
//     lowPassFrequency: 22050,
//     pitch: 1,
//     isMuted: false,
//     src: '../../../assets/samples/Perc 37- Kitdepontos.COm.Br.wav',
//     playable: new Array<boolean>(32).fill(false),
//     buffer: '',
//     key: 'o'
// }]
const breakbeat: Snippet[] = [{
    name: 'Kick 13',
    fileName: 'HouseGen Kick 13.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/breatbeat/HouseGen%20Kick%2013.wav',
    playable: [true, false, false, true, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, true, true, false, false, true, false, false, false, true, false],
    buffer: '',
    key: 'q',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Snare 36',
    fileName: 'Attack Snare 36.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/breatbeat/Attack%20Snare%2036.wav',
    playable: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
    buffer: '',
    key: 'p',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Snare 14',
    fileName: 'HouseGen Snare 14.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/breatbeat/HouseGen%20Snare%2014.wav',
    playable: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
    buffer: '',
    key: 'o',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Attack Hat 17',
    fileName: 'Attack Hat 17.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/breatbeat/Attack%20Hat%2017.wav',
    playable: [false, true, true, true, true, false, true, true, false, true, true, false, true, false, true, false, true, true, true, false, true, true, true, true, true, true, true, true, false, true, true, true],
    buffer: '',
    key: 'i',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Collider Fifth ii',
    fileName: 'Collider Fifth ii.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/breatbeat/Collider%20Fifth%20ii.wav',
    playable: [false, false, false, true, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, true, false],
    buffer: '',
    key: 'w',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'MA Lid Pop 02',
    fileName: 'MA Lid Pop 02.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/breatbeat/MA%20Lid%20Pop%2002.wav',
    playable: [false, false, true, false, false, false, false, true, false, true, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, true, true, false, false, false, true, false],
    buffer: '',
    key: 'r',
    startTime: 0,
    endTime: 0,
    swing: 0
},]
const defunk = [{
    name: 'GRAVE NOGUEIRA',
    fileName: 'GRAVE NOGUEIRA.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/defunk/GRAVE%20NOGUEIRA.wav',
    playable: [true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false],
    buffer: '',
    key: 'q',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'E Xtreme Man D E L Ã O_13 - Kitdepontos. C Om. Br',
    fileName: 'E Xtreme Man D E L Ã O_13 - Kitdepontos. C Om. Br.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/defunk/E%20Xtreme%20Man%20D%20E%20L%20%C3%83%20O_13%20-%20Kitdepontos.%20C%20Om.%20Br.wav',
    playable: [false, false, false, true, false, false, true, false, false, false, false, true, false, false, true, false, false, false, false, true, false, false, true, false, false, false, false, true, false, false, true, false],
    buffer: '',
    key: 'p',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Sound 28 - Kitdepontos..COm.Br',
    fileName: 'Sound 28 - Kitdepontos..COm.Br.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/defunk/Sound%2028%20-%20Kitdepontos..COm.Br.wav',
    playable: [false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, false],
    buffer: '',
    key: 'o',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Sound 5 - Kitdepontos..COm.Br',
    fileName: 'Sound 5 - Kitdepontos..COm.Br.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/defunk/Sound%205%20-%20Kitdepontos..COm.Br.wav',
    playable: [false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false],
    buffer: '',
    key: 'i',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Hã - MC Don Juan',
    fileName: 'Hã - MC Don Juan.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/defunk/H%C3%A3%20-%20MC%20Don%20Juan.wav',
    playable: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
    buffer: '',
    key: 'w',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'sample N.10 DJ CASPA ORIGINAL ',
    fileName: 'sample N.10 DJ CASPA ORIGINAL .wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/defunk/sample%20N.10%20DJ%20CASPA%20ORIGINAL%20.wav',
    playable: [false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, false, false],
    buffer: '',
    key: 'r',
    startTime: 0,
    endTime: 0,
    swing: 0
},]
const house = [{
    name: 'HouseGen Kick 06',
    fileName: 'HouseGen Kick 06.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/house/HouseGen%20Kick%2006.wav',
    playable: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
    buffer: '',
    key: 'q',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Attack Snare 25',
    fileName: 'Attack Snare 25.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/house/Attack%20Snare%2025.wav',
    playable: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
    buffer: '',
    key: 'p',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Attack Clap 20',
    fileName: 'Attack Clap 20.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/house/Attack%20Clap%2020.wav',
    playable: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
    buffer: '',
    key: 'o',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Attack Hat 02',
    fileName: 'Attack Hat 02.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/house/Attack%20Hat%2002.wav',
    playable: [false, false, true, true, false, false, true, false, false, true, true, true, false, false, true, false, false, true, true, true, false, false, true, false, false, false, true, true, false, false, true, false],
    buffer: '',
    key: 'i',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Attack OHat 02',
    fileName: 'Attack OHat 02.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/house/Attack%20OHat%2002.wav',
    playable: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
    buffer: '',
    key: 'w',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Hyper GoldenDays Clave',
    fileName: 'Hyper GoldenDays Clave.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/house/Hyper%20GoldenDays%20Clave.wav',
    playable: [false, false, true, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, true],
    buffer: '',
    key: 'r',
    startTime: 0,
    endTime: 0,
    swing: 0
},]
const drill = [{
    name: 'EAGLE KICK',
    fileName: 'EAGLE KICK.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/drill/EAGLE%20KICK.wav',
    playable: [true, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false],
    buffer: '',
    key: 'q',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'CLASSIC REMAKE SNARE',
    fileName: 'CLASSIC REMAKE SNARE.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/drill/CLASSIC%20REMAKE%20SNARE.wav',
    playable: [false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
    buffer: '',
    key: 'p',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'CLASSIC HH',
    fileName: 'CLASSIC HH.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/drill/CLASSIC%20HH.wav',
    playable: [false, false, false, true, false, false, true, false, true, false, true, true, false, false, true, false, false, true, true, true, false, false, true, false, false, false, true, true, false, true, true, true],
    buffer: '',
    key: 'o',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'FOREIGN PERC',
    fileName: 'FOREIGN PERC.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/drill/FOREIGN%20PERC.wav',
    playable: [false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, true, false],
    buffer: '',
    key: 'i',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'EL CASA 808 ',
    fileName: 'EL CASA 808 .wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/drill/EL%20CASA%20808%20.wav',
    playable: [true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false],
    buffer: '',
    key: 'w',
    startTime: 0,
    endTime: 0,
    swing: 0
},]
const jerseyClub = [{
    name: 'It\'s Dynamite - Heavy Brick ( Kick )',
    fileName: 'It\'s Dynamite - Heavy Brick ( Kick ).wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: `https://storage.googleapis.com/test022123/samples/jersey%20club/It's%20Dynamite%20-%20Heavy%20Brick%20(%20Kick%20).wav`,
    playable: [true, false, false, false, true, false, false, false, true, false, false, true, false, false, true, false, true, false, false, false, true, false, false, false, true, false, false, true, false, false, true, false],
    buffer: '',
    key: 'q',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'It\'s Dynamite - Ez ( Hi Hat )',
    fileName: 'It\'s Dynamite - Ez ( Hi Hat ).wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: `https://storage.googleapis.com/test022123/samples/jersey%20club/It's%20Dynamite%20-%202012%20(%20Snare%20).wav`,
    playable: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
    buffer: '',
    key: 'p',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'It\'s Dynamite - Ez ( Hi Hat )',
    fileName: 'It\'s Dynamite - Ez ( Hi Hat ).wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: `https://storage.googleapis.com/test022123/samples/jersey%20club/It's%20Dynamite%20-%20Ez%20(%20Hi%20Hat%20).wav`,
    playable: [false, false, true, true, false, false, true, false, true, false, true, false, true, false, true, false, false, false, true, true, true, false, true, false, true, true, true, false, true, false, true, false],
    buffer: '',
    key: 'o',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'It\'s Dynamite - Hip ( Hi Hat )',
    fileName: 'It\'s Dynamite - Hip ( Hi Hat ).wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: `https://storage.googleapis.com/test022123/samples/jersey%20club/It's%20Dynamite%20-%20Hip%20(%20Hi%20Hat%20).wav`,
    playable: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
    buffer: '',
    key: 'i',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'It\'s Dynamite - Row ( Vox )',
    fileName: 'It\'s Dynamite - Row ( Vox ).wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: `https://storage.googleapis.com/test022123/samples/jersey%20club/It's%20Dynamite%20-%20Row%20(%20Vox%20).wav`,
    playable: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, true, false, false, true, false],
    buffer: '',
    key: 'w',
    startTime: 0,
    endTime: 0,
    swing: 0
},]
const techno = [{
    name: 'Power LongKick 09',
    fileName: 'Power LongKick 09.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: `https://storage.googleapis.com/test022123/samples/techno/Power%20LongKick%2009.wav`,
    playable: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
    buffer: '',
    key: 'q',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Attack Hat 27',
    fileName: 'Attack Hat 27.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: `https://storage.googleapis.com/test022123/samples/techno/Attack%20Hat%2027.wav`,
    playable: [false, true, true, true, false, false, true, false, false, false, true, false, false, true, true, true, false, true, true, true, false, false, true, false, false, false, true, false, false, true, true, false],
    buffer: '',
    key: 'p',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Collider Tuned Warp Glock 01',
    fileName: 'Collider Tuned Warp Glock 01.wav',
    volume: 0.5,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: `https://storage.googleapis.com/test022123/samples/techno/Collider%20Tuned%20Warp%20Glock%2001.wav`,
    playable: [false, false, false, false, false, false, true, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false],
    buffer: '',
    key: 'o',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Collider Sub Shaker',
    fileName: 'Collider Sub Shaker.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: `https://storage.googleapis.com/test022123/samples/techno/Collider%20Sub%20Shaker.wav`,
    playable: [false, false, true, false, false, true, true, false, true, true, true, false, true, true, false, false, false, true, true, false, true, true, true, false, false, true, true, false, true, true, true, false],
    buffer: '',
    key: 'i',
    startTime: 0,
    endTime: 0,
    swing: 0
},]
const boombap = [{
    name: 'Hyper RagsToRiches Kick 01',
    fileName: 'Hyper RagsToRiches Kick 01.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/boombap/Hyper%20RagsToRiches%20Kick%2001.wav',
    playable: [true, false, false, false, false, false, true, false, false, false, true, true, false, false, false, false, false, true, true, false, false, false, true, false, false, false, false, true, false, false, true, false],
    buffer: '',
    key: 'q',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Downstream Snare 06',
    fileName: 'Downstream Snare 06.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/boombap/Downstream%20Snare%2006.wav',
    playable: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
    buffer: '',
    key: 'p',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Attack Clap 05',
    fileName: 'Attack Clap 05.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/boombap/Attack%20Clap%2005.wav',
    playable: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, true, false],
    buffer: '',
    key: 'o',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Attack Hat 27',
    fileName: 'Attack Hat 27.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/boombap/Attack%20Hat%2027.wav',
    playable: [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, true, true, false, true, false, true, false, true, false, true, false, true, true, true, false, true, false],
    buffer: '',
    key: 'i',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'MA Charcoal Planetary Perc',
    fileName: 'MA Charcoal Planetary Perc.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/boombap/MA%20Charcoal%20Planetary%20Perc.wav',
    playable: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
    buffer: '',
    key: 'w',
    startTime: 0,
    endTime: 0,
    swing: 0
}, {
    name: 'Attack AnalogBell 01',
    fileName: 'Attack AnalogBell 01.wav',
    volume: 1,
    pan: 0,
    highPassFrequency: 0,
    lowPassFrequency: 22050,
    pitch: 1,
    isMuted: false,
    src: 'https://storage.googleapis.com/test022123/samples/boombap/Attack%20AnalogBell%2001.wav',
    playable: [false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, false, true, false, false, false, false, false, false, true, false],
    buffer: '',
    key: 'r',
    startTime: 0,
    endTime: 0,
    swing: 0
},]

const presets: Map<string, Session> = new Map();
// const defaultKitPreset: Session = {
//     name: "default",
//     type: 'preset',
//     bpm: 125,
//     length: 32,
//     snippets: defaultKit
// }
// presets.set('default', defaultKitPreset)
const breakbeatPreset: Session = {
    name: " breakbeat",
    type: 'preset',
    bpm: 135,
    length: 32,
    snippets: breakbeat
}
presets.set('breakBeat', breakbeatPreset)
const defunkPreset: Session = {
    name: "defunk",
    type: 'preset',
    bpm: 130,
    length: 32,
    snippets: defunk
}
presets.set('defunk', defunkPreset)
const housePreset: Session = {
    name: "house",
    type: 'preset',
    bpm: 125,
    length: 32,
    snippets: house
}
presets.set('house', housePreset)
const drillPreset: Session = {
    name: "house",
    type: 'preset',
    bpm: 140,
    length: 32,
    snippets: drill
}
presets.set('drill', drillPreset)
const jerseyClubPreset: Session = {
    name: "drill",
    type: 'preset',
    bpm: 132,
    length: 32,
    snippets: jerseyClub
}
presets.set('jersey Club', jerseyClubPreset)
const technoPreset: Session = {
    name: "jersey club",
    type: 'preset',
    bpm: 128,
    length: 32,
    snippets: techno
}
presets.set('techno', technoPreset)
const boombapPreset: Session = {
    name: "Boom bap",
    type: 'preset',
    bpm: 95,
    length: 32,
    snippets: boombap
}
presets.set('Boom bap', boombapPreset)

export { presets };